 image: "maven:3.3.9-jdk-8"
 services:
     - "mysql:5.7.26"
 maven-install:
    script: "mvn install"
    stage: install
 maven-test:
    script: "mvn test"
    stage: test
 stages:
    - test
    - install
 variables:
    MYSQL_ROOT_PASSWORD: root123
    MYSQL_DATABASE: userDb
    MYSQL_USER: app-root
    MYSQL_PASSWORD: root123
    MYSQL_HOST: mysql