# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file
version: '3'
services:
 UserAuthentication-Service:
  image: lokeshkotkar/UserAuthentication-Service:latest
  restart: always
  network_mode: host
  container_name: authServiceCon
  depends_on: 
  - mysql
  ports:
  - 8089:8089
  
 UserService:
  image: lokeshkotkar/UserService:latest
  restart: always
  network_mode: host
  container_name: userServiceCon
  depends_on: 
  - mongo
  ports:
  - 8080:8080
  
 NoteService:
  image: lokeshkotkar/NoteService:latest
  restart: always
  network_mode: host
  container_name: noteServiceCon
  depends_on: 
  - mongo
  ports:
  - 8082:8082
  
 ReminderService:
  image: lokeshkotkar/ReminderService:latest
  restart: always
  network_mode: host
  container_name: reminderServiceCon
  depends_on: 
  - mongo
  ports:
  - 8081:8081
  
 CategoryService:
  image: lokeshkotkar/CategoryService:latest
  restart: always
  network_mode: host
  container_name: categoryServiceCon
  depends_on: 
  - mongo
  ports:
  - 8083:8083
  
  
 mysql :
  image: mysql:5.5
  ports: 
  - 3306:3306
  container_name: mysql_container
  network_mode: host
  environment: 
   MYSQL_DATABASE=userDb
   MYSQL_USER=app-root
   MYSQL_PASSWORD=root
   MYSQL_HOST=localhost
   MYSQL_URL=jdbc:mysql://localhost:3306/userDb
   
  mongo: 
   image: mongo-3.2-jessie
   ports: 
   - 27017:27017
   container_name: mongo
   network_mode: host


